# Generated by Django 5.2.13 on 2026-04-15 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('education', '0004_remove_resource_model_url_resource_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='model_file',
            field=models.FileField(blank=True, null=True, upload_to='devices/models/'),
        ),
        migrations.AddField(
            model_name='device',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='education.topic'),
        ),
    ]
