# Generated by Django 5.2.13 on 2026-04-15 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_course_resource_topic_delete_lesson_quiz_explanation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='node_names',
        ),
        migrations.CreateModel(
            name='ResourceNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='education.resource')),
            ],
            options={
                'verbose_name': 'Resource Node',
                'verbose_name_plural': 'Resource Nodes',
                'ordering': ['resource', 'order', 'name'],
            },
        ),
    ]
