# Generated by Django 5.2.13 on 2026-04-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_remove_resource_node_names_resourcenode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='model_url',
        ),
        migrations.AddField(
            model_name='resource',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='education/resources/images/'),
        ),
        migrations.AddField(
            model_name='resource',
            name='model_file',
            field=models.FileField(blank=True, null=True, upload_to='education/resources/models/'),
        ),
        migrations.AddField(
            model_name='resource',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='education/resources/files/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('link', 'Link'), ('3d_model', '3D Model')], default='text', max_length=20),
        ),
    ]
