# Generated by Django 5.2.13 on 2026-04-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_remove_resource_model_url_resource_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='model_file',
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('link', 'Link')], default='text', max_length=20),
        ),
    ]
