# Generated by Django 5.2.13 on 2026-05-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_savedcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='full_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
